# Oyuncular di�er oyunculara zarar verebilir.
PVP=true

# Sunucuda hi� oyuncu yoksa oyun d�nyas�n�n zaman� durur.
PauseEmpty=true

# Genel sohbetin kullan�l�p kullan�lmayaca��n� belirler.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# Oyuncular, whitelist'te bulunmasalar bile sunucuya ba�lanabilir. E�er bu de�er false yap�l�rsa, adminler kullan�c� ad� ve parolalar� manuel olarak sisteme girmelidir.
Open=true

# Bu mesaj, bir istemci oyuna ba�land���nda onun sohbet ekran�nda g�r�nt�lenecektir.
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

# Oyuncular ba�land��� zaman, bilinmeyen kullan�c� adlar�n� whitelist'e ekleyebilirsiniz.  Open
AutoCreateUserInWhiteList=false

# Karakterin �st�nde oyuncunun kullan�c� ad�n� g�sterir.
DisplayUserName=true

# Kullan�c� ad� yerine oyuncunun ba�lar�n�n �st�nde oyundaki ad� ve soyad�n� g�ster.
ShowFirstAndLastName=false

# B�t�n yeni oyuncular�, belirlenen X,Y,Z koordinatlar�nda do�maya zorlar. Koordinatlar� map.projectzomboid.com adresinden ��renebilirsiniz.
# 0,0,0 iken yok say�l�r.
SpawnPoint=0,0,0

# Oyuncular PVP moduna girebilir.  Bir oyuncu di�er oyuncuya bir ya da ikisinin de PVP modu a��ksa zarar verebilir.  SafetySystem
SafetySystem=true

# Oyuncular PVP moduna girdi�i zaman karakterlerin �st�nde bir kurukafa simgesi g�z�k�r.
ShowSafety=true

# Oyuncunun PVP moduna girerken veya ��karken bekleyece�i zamand�r.\nMinimum=0 Maximum=1000 Varsay�lan=2
SafetyToggleTimer=2

# Oyuncunun tekrar PVP moduna girmeden veya ��kmadan bekleyece�i gecikme (cooldown) s�residir.\nMinimum=0 Maximum=1000 Varsay�lan=3
SafetyCooldownTimer=3

# Yeni oyuncular�n hangi e�yalar ile ba�layaca��n� belirler.\nBirden �ok ��eleri virg�l ile ay�r�n.\n�rn: Base.Axe,Base.BigHikingBag
SpawnItems=

# Oyuncu verileri i�in ba�lang�� portu. E�er UDP ise, bu kullan�lan iki porttan biridir. E�er legacy TCP ise, bu port ile ba�layan her oyuncu i�in bir port kullan�l�r.\nMinimum=0 Maximum=65535 Varsay�lan=16261
DefaultPort=16261

# Minimum=0 Maximum=65535 Varsay�lan=16262
UDPPort=16262

# Sunucuda s�f�rlanma i�leminin yap�l�p yap�lmad���n� belirlemek i�in kullan�l�r. Bu say� istemci ile e�le�iyorsa, istemcinin yeni bir karakter olu�turmas� gerekmektedir. PlayerServerID ile ba�lant�l�d�r. L�tfen, bu kimlikleri bir yere yedekleyin.\nMinimum=0 Maximum=2147483647 Varsay�lan=147360703
ResetID=147360703

# Modun ID kimli�ini buraya girin. ID kimli�i �u dosyada bulunabilir: \Steam\steamapps\workshop\modID\mods\modAd�\info.txt
Mods=Mod_3680633169

# Modun klas�r ad�n� buraya girin. �rne�in: \Steam\steamapps\workshop\modID\mods\modAd�\media\maps\
Map=Muldraugh, KY

# �stemcinin dosyalar� sunucu ile uyu�mad��� zaman oyuncuyu otomatik olarak sunucudan atar.
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Sunucuyu, oyun i�indeki sunucu listesinde listeler.
# Not: Steam onayl� sunucular, her zaman Steam'in sunucu taray�c�s�nda g�r�nt�lenir.
Public=false

# Oyun i�inde ve Steam sunucu listesinde (varsa) g�sterilecek sunucu ad�.
PublicName=My PZ Server

# Oyun i�indeki sunucu listesinde g�sterilecek sunucu a��klamas�.
PublicDescription=

# Adminler hari�, sunucuya e� zamanl� olarak ba�lanabilecek maksimum oyuncu say�s�.
# Steam, maksimum 126 oyuncuya izin verir.\nMinimum=1 Maximum=100 Varsay�lan=32
MaxPlayers=32

# Milisaniye baz�nda, sunucudan at�lmadan �nceki ping s�n�r�. Devre d��� b�rakmak i�in 0 de�eri girilmelidir.\nMinimum=100 Maximum=2147483647 Varsay�lan=400
PingLimit=400

# B�lge, e�yalar�n yeniden do�mas� i�in oyun i�i saat ile bu kadar saat g�r�lmemi� olmal�d�r.  Sandbox'daki 'Lootlar�n Yeniden Do�mas�' ayar� yok say�l�r.\nMinimum=0 Maximum=2147483647 Varsay�lan=0
HoursForLootRespawn=0

# Depolama alanlar�na bu kadar e�ya do�mu�sa o depolama alan�nda bir daha hi� e�ya do�maz.\nMinimum=1 Maximum=2147483647 Varsay�lan=4
MaxItemsForLootRespawn=4

# E�yalar, e�er bir oyuncu o b�lgede yap�lar in�a etmi� ise yeniden do�maz.
ConstructionPreventsLootRespawn=true

# Oyuncu �ld�kten sonra, oyuncunun kullan�c� hesab� whitelist'ten silinir. Open
DropOffWhiteListAfterDeath=false

# Kamp ate�i hari�, sunucuda olu�abilecek herhangi bir yang�n t�r�n� devre d��� b�rak�r.
NoFire=false

# E�er true ise, her zaman sunucunun sohbet ekran�nda oyuncular�n �l�m mesajlar� g�sterilir.
AnnounceDeath=false

# Kitab�n bir sayfas�n�n oyun i�i dakika ile ne kadar s�rede okunaca��n� belirler.\nMinimum=0,00 Maximum=60,00 Varsay�lan=1,00
MinutesPerPage=1.0

# Haritan�n y�kl� par�alar� ger�ek zamanla bu kadar dakika ge�tikten sonra kaydedilir.  Harita genellikle istemci y�klenmi� b�lgeden ayr�ld��� zaman kaydedilir.\nMinimum=0 Maximum=2147483647 Varsay�lan=0
SaveWorldEveryMinutes=0

# Oyuncular s���nak (safehouse) sahiplenebilir.
PlayerSafehouse=false

# Sadece adminler s���nak (safehouse) sahiplenebilir.
AdminSafehouse=false

# S���nak �yesi olmayanlar�n s���na�a girmesine izin verir.
SafehouseAllowTrepass=true

# S���naklarda yang�n ��kmas�na ve ��kar�lmas�na izin verir.
SafehouseAllowFire=true

# S���nak �yesi olmayanlar�n s���naktan e�ya almalar�na izin verir.
SafehouseAllowLoot=true

# Oyuncular �ld��� zaman, �ye olduklar� s���naklar�nda yeniden do�arlar.
SafehouseAllowRespawn=false

# Oyuncular, s���nak sahiplenebilmek i�in oyun i�i zaman ile bu kadar g�n hayatta kalm�� olmal�d�r.\nMinimum=0 Maximum=2147483647 Varsay�lan=0
SafehouseDaySurvivedToClaim=0

# Oyuncular, ger�ek zamanla bu kadar saat i�inde s���na�� ziyaret etmediklerinde, s���nak �yeli�inden otomatik olarak silinirler.\nMinimum=0 Maximum=2147483647 Varsay�lan=144
SafeHouseRemovalTime=144

# Oyuncular�n konut d��� binalar� talep edip edemeyece�ini belirler.
SafehouseAllowNonResidential=false

# Oyuncular�n balyoz ile d�nya objelerini yok etmesine izin verir.
AllowDestructionBySledgehammer=true

# Oyuncular�n d�nya nesnelerini yaln�zca g�venli evlerinde yok etmelerine izin verin (AllowDestructionBySledgehammer '�n true olmas�n� gerektirir).
SledgehammerOnlyInSafehouse=false

# M�mk�n olandan daha h�zl� giden oyuncular� oyundan atar.
KickFastPlayers=false

# Karakterin ba�ka bir sunucudan m� yoksa tek oyunculu moddan m� oldu�unu belirlemek i�in kullan�l�r. Bu de�er soft-reset ile de�i�tirilebilir. Bu say� istemci ile e�le�iyorsa, istemcinin yeni bir karakter olu�turmas� gerekmektedir. ResetID ile ba�lant�l�d�r. L�tfen, bu kimlikleri bir yere yedekleyin.
ServerPlayerID=2111444145

# RCON ba�lant�s� i�in bir port se�in.\nMinimum=0 Maximum=65535 Varsay�lan=27015
RCONPort=27015

# RCON �ifresini belirler.
RCONPassword=

# Discord ile entegrasyonu etkinle�tir
DiscordEnable=false

# Discord bot eri�im tokeni
DiscordToken=

# Discord kanal ad�. Bununla ilgili baz� sorunlar�n�z varsa, bunun yerine kanal kimli�ini kullan�n
DiscordChannel=

# Discord kanal kimli�i. Zorunlu de�ildir. Kanal ad�yla ilgili sorun olmas� durumunda kullan�n
DiscordChannelID=

# �stemciler sunucuya ba�lanabilmek i�in bu �ifreyi bilmek zorundad�r. Host b�l�m�nden sunucu kuruldu�u zaman yok say�l�r.
Password=

# Tek bir Steam kullan�c�s�n�n bu sunucuda birden �ok hesap (karakter) ile oynamas�n� s�n�rlar. Steam sunucusu kuruldu�u zaman yok say�l�r.\nMinimum=0 Maximum=2147483647 Varsay�lan=0
MaxAccountsPerUser=0

# Allow co-op/splitscreen players
AllowCoop=true

# Oyuncular istedi�i zaman uyuyabilir.
SleepAllowed=false

# Oyuncular yorulur ve uykuya ihtiya� duyarlar.  SleepAllowed
SleepNeeded=false

KnockedDownAllowed=true

SneakModeHideFromOtherPlayers=true

# Sunucuya indirilecek At�lye Mod'lar�n� listelemek i�in kullan�l�r. Noktal� virg�lle ayr�lmal�d�r. �rnek: WorkshopItems
WorkshopItems=3680633169

# Oyuncular listesinde Steam kullan�c� adlar�n� ve avatarlar�n� g�ster.\nBu ayar true, false veya admin olabilir.
SteamScoreboard=true

# Steam VAC sistemi kullan�l�r.
SteamVAC=true

# UPnP �zellikli internet a� ge�idini otomatik olarak port y�nlendirme kurallar�n� almas� i�in yap�land�r�r.
UPnP=true

# E�er true ise, VOIP etkinle�tirilecektir.
VoiceEnable=true

# VOIP seslerinin duyulabilece�i minimum mesafe.\nMinimum=0,00 Maximum=100000,00 Varsay�lan=10,00
VoiceMinDistance=10.0

# VOIP seslerinin duyulabilece�i maksimum mesafe.\nMinimum=0,00 Maximum=100000,00 Varsay�lan=100,00
VoiceMaxDistance=100.0

# VOIP i�in 3D ses.
Voice3D=true

# Minimum=10,00 Maximum=150,00 Varsay�lan=70,00
SpeedLimit=70.0

LoginQueueEnabled=false

# Minimum=20 Maximum=1200 Varsay�lan=60
LoginQueueConnectTimeout=60

# Sunucunun yay�nlanaca�� IP adresini ayarlay�n. Sunucu gruplar� gibi birden �ok IP adresine sahip a� yap�land�rmalar� i�indir.
server_browser_announced_ip=

# Oyuncular �ld�kleri yerde tekrar yeniden do�abilirler.
PlayerRespawnWithSelf=false

# Oyuncu Ba�ka Bir Oyuncunun Yan�nda Yeniden Ba�layabilir
PlayerRespawnWithOther=false

# Herkes uyudu�u zaman, oyun zaman� ne kadar h�zl� ilerleyecek?\nMinimum=1,00 Maximum=100,00 Varsay�lan=40,00
FastForwardMultiplier=40.0

# E�er zaten sahip olunan bir s���na�� sahiplenmeye kalkan olursa, s���nak normal bir ev gibi g�z�kecektir.
DisableSafehouseWhenPlayerConnected=false

# E�er true ise, oyuncular�n grup olu�turmalar�na izin verir.
Faction=true

# Bir grup olu�turmadan �nce X g�n boyunca hayatta kalm�� olman�z gerekmektedir.\nMinimum=0 Maximum=2147483647 Varsay�lan=0
FactionDaySurvivedToCreate=0

# Grup sahibinin, �zel bir isim etiketi olu�turmadan �nce grupta ne kadar �ye olmas� gerekti�ini belirler.\nMinimum=1 Maximum=2147483647 Varsay�lan=1
FactionPlayersRequiredForTag=1

# Herhangi bir eri�im seviyesine sahip oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioStaff=false

# 'Y�netici' eri�im d�zeyine sahip oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioAdmin=true

# 'GM' eri�im d�zeyine sahip oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioGM=true

# '�dareci' eri�im d�zeyine sahip oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioOverseer=false

# 'Moderat�r' eri�im d�zeyine sahip oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioModerator=false

# G�r�nmez oyunculardan radyo yay�nlar�n� almay� devre d��� b�rak�r.
DisableRadioInvisible=true

# Cmd.txt sunucu g�nl���ne yaz�lmayacak olan komutlar�n noktal� virg�lle ayr�lm�� listesi.\n-vehicle.* de�eri herhangi bir ara� komutunun yaz�lmamas� anlam�na gelir.\n+vehicle.installPart de�eri ge�erli komutun yaz�lmas� anlam�na gelir.
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# ClientActionLogs.txt sunucu g�nl���ne yaz�lacak eylemlerin noktal� virg�lle ayr�lm�� listesi.
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# PerkLog.txt sunucu g�nl���nde oyuncu Beceri d�zeylerindeki de�i�iklikleri izleyin
PerkLogs=true

# Bir depolama alan�na yerle�tirilebilecek maksimum ��e say�s�. S�f�r de�eri s�n�r yok anlam�na gelir.\nMinimum=0 Maximum=9000 Varsay�lan=0
ItemNumbersLimitPerContainer=0

# Eski kan lekelerinin kald�r�lmas�ndan �nceki g�n say�s�.
# Kald�rma, harita par�alar� y�klendi�inde ger�ekle�ir.
# S�f�r, hi�bir zaman kald�rmayacak anlam�na gelir.\nMinimum=0 Maximum=365 Varsay�lan=0
BloodSplatLifespanDays=0

# Kullan�c� ad�nda Ascii olmayan (kiril...) karakterlerin kullan�m�na izin verin veya vermeyin
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Do�ruysa, HoursForCorpseRemoval tetiklendi�inde, oyuncular�n cesetlerini de kald�racakt�r.
RemovePlayerCorpsesOnCorpseRemoval=false

# A��ksa oyuncu ��p kutular�ndaki hepsini sil tu�unu kullanabilir
TrashDeleteAll=false

# E�er a��ksa oyuncu ba�ka bir oyuncu taraf�ndan vuruldu�unda tekrar vurabilir.
PVPMeleeWhileHitReaction=false

# A��ksa, oyuncular�n adlar� g�rebilmek i�in fareyi birinin �zerine getirmesi gerekir.
MouseOverToSeeDisplayName=true

# A��ksa, g�remediklerinizi (zombiler gibi) otomatik olarak gizleyin.
HidePlayersBehindYou=true

# Yak�n D�v�� PVP ��in Hasar Ayar�\nMinimum=0,00 Maximum=500,00 Varsay�lan=30,00
PVPMeleeDamageModifier=30.0

# Menzilli PVP ��in Hasar Ayar�\nMinimum=0,00 Maximum=500,00 Varsay�lan=50,00
PVPFirearmDamageModifier=50.0

# Arabalar�n zombileri �ekme aral���n� de�i�tirin, daha d���k de�erler sunucu gecikmelerine(lag) yard�mc� olabilir.\nMinimum=0,00 Maximum=10,00 Varsay�lan=0,50
CarEngineAttractionModifier=0.5

# Oyuncular ko�arken birbirlerini �arparak itebilir.
PlayerBumpPlayer=false

# Oyun i�i haritada uzaktaki oyuncular�n g�r�nt�lenmesini kontrol eder.\n1\nMinimum=1 Maximum=3 Varsay�lan=1
MapRemotePlayerVisibility=1

# Minimum=1 Maximum=300 Varsay�lan=5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# Minimum=0 Maximum=1500 Varsay�lan=0
BackupsPeriod=0

# Tip 1 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType1=true

# Tip 2 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType2=true

# Tip 3 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType3=true

# Tip 4 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType4=true

# Tip 5 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType5=true

# Tip 6 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType6=true

# Tip 7 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType7=true

# Tip 8 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType8=true

# Tip 9 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType9=true

# Tip 10 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType10=true

# Tip 11 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType11=true

# Tip 12 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType12=true

# Tip 13 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType13=true

# Tip 14 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType14=true

# Tip 15 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType15=true

# Tip 16 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType16=true

# Tip 17 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType17=true

# Tip 18 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType18=true

# Tip 19 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType19=true

# Tip 20 i�in hileye kar�� korumay� devre d��� b�rak�r.
AntiCheatProtectionType20=true

AntiCheatProtectionType21=true

AntiCheatProtectionType22=true

AntiCheatProtectionType23=true

AntiCheatProtectionType24=true

# Tip 2 ��in Hile �nleme korumas�  e�ik de�er �arpan�\nMinimum=1,00 Maximum=10,00 Varsay�lan=3,00
AntiCheatProtectionType2ThresholdMultiplier=3.0

# Tip 3 i�in hileye kar�� korumay� devre d��� b�rak�r.\nMinimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType3ThresholdMultiplier=1.0

# Tip 4 ��in Hile �nleme korumas�  e�ik de�er �arpan�\nMinimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType4ThresholdMultiplier=1.0

# Tip 9 ��in Hile �nleme korumas�  e�ik de�er �arpan�\nMinimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType9ThresholdMultiplier=1.0

# Tip 15 ��in Hile �nleme korumas�  e�ik de�er �arpan�\nMinimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType15ThresholdMultiplier=1.0

# Tip 20 i�in hileye kar�� korumay� devre d��� b�rak�r.\nMinimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType20ThresholdMultiplier=1.0

# Minimum=1,00 Maximum=10,00 Varsay�lan=1,00
AntiCheatProtectionType22ThresholdMultiplier=1.0

# Minimum=1,00 Maximum=10,00 Varsay�lan=6,00
AntiCheatProtectionType24ThresholdMultiplier=6.0