SandboxVars = {
    VERSION = 5,
    -- Bunu deðiþtirmek, geliþmiþ ayarlardaki \Nüfus Çarpaný\ ayarýný etkiler. Varsayýlan= Normal
    -- 1 = En Yüksek
    -- 2 = Çok Yüksek
    -- 3 = Yüksek
    -- 4 = Normal
    -- 5 = Az
    Zombies = 4,
    -- Varsayýlan= Þehir Odaklý
    -- 1 = Þehir Odaklý
    Distribution = 1,
    -- Varsayýlan= 1 Saat
    -- 1 = 15 Dakika
    -- 2 = 30 Dakika
    -- 3 = 1 Saat
    -- 4 = 2 Saat
    -- 5 = 3 Saat
    -- 6 = 4 Saat
    -- 7 = 5 Saat
    -- 8 = 12 Saat
    -- 9 = Gerçek Zamanlý
    -- 10 = 8 Saat
    -- 11 = 9 Saat
    -- 12 = 10 Saat
    -- 13 = 11 Saat
    -- 14 = 12 Saat
    -- 15 = 13 Saat
    -- 16 = 14 Saat
    -- 17 = 15 Saat
    -- 18 = 16 Saat
    -- 19 = 17 Saat
    -- 20 = 18 Saat
    -- 21 = 19 Saat
    -- 22 = 20 Saat
    -- 23 = 21 Saat
    -- 24 = 22 Saat
    -- 25 = 23 Saat
    DayLength = 3,
    StartYear = 1,
    -- Varsayýlan= Temmuz
    -- 1 = Ocak
    -- 2 = Þubat
    -- 3 = Mart
    -- 4 = Nisan
    -- 5 = Mayýs
    -- 6 = Haziran
    -- 7 = Temmuz
    -- 8 = Aðustos
    -- 9 = Eylül
    -- 10 = Ekim
    -- 11 = Kasým
    StartMonth = 7,
    StartDay = 9,
    -- Varsayýlan= 9:00
    -- 1 = 7:00
    -- 2 = 9:00
    -- 3 = 12:00
    -- 4 = 14:00
    -- 5 = 17:00
    -- 6 = 21:00
    -- 7 = 00:00
    -- 8 = 02:00
    StartTime = 2,
    -- Varsayýlan= 0-30 Gün
    -- 1 = Anlýk
    -- 2 = 0-30 Gün
    -- 3 = 0-2 Ay
    -- 4 = 0-6 Ay
    -- 5 = 0-1 Yýl
    -- 6 = 0-5 Yýl
    -- 7 = 2-6 Ay
    WaterShut = 2,
    -- Varsayýlan= 0-30 Gün
    -- 1 = Anlýk
    -- 2 = 0-30 Gün
    -- 3 = 0-2 Ay
    -- 4 = 0-6 Ay
    -- 5 = 0-1 Yýl
    -- 6 = 0-5 Yýl
    -- 7 = 2-6 Ay
    ElecShut = 2,
    -- Minimum=-1 Maximum=2147483647 Varsayýlan=14
    WaterShutModifier = 14,
    -- Minimum=-1 Maximum=2147483647 Varsayýlan=14
    ElecShutModifier = 14,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    FoodLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    CannedFoodLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    LiteratureLoot = 4,
    -- Tohumlar, testere, çiviler, çeþitli aletler, sabitleyiciler, olta ... Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    SurvivalGearsLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    MedicalLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    WeaponLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    RangedWeaponLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    AmmoLoot = 4,
    -- Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    MechanicsLoot = 4,
    -- Everything else. Also affects foraging for all items in Town/Road zones. Varsayýlan= Nadir
    -- 1 = Yok
    -- 2 = Ýnanýlmaz Nadir
    -- 3 = Çok Nadir
    -- 4 = Nadir
    -- 5 = Normal
    -- 6 = Yaygýn
    OtherLoot = 4,
    -- Küresel sýcaklýðý kontrol eder. Varsayýlan= Normal
    -- 1 = Çok Soðuk
    -- 2 = Soðuk
    -- 3 = Normal
    -- 4 = Sýcak
    Temperature = 3,
    -- Ne kadar sýklýkla yaðmur yaðacaðýný belirler. Varsayýlan= Normal
    -- 1 = Çok Kurak
    -- 2 = Kurak
    -- 3 = Normal
    -- 4 = Yaðýþlý
    Rain = 3,
    -- Erozyonun yüzde yüze ulaþma süresi. Varsayýlan= Normal (100 Gün)
    -- 1 = Çok Hýzlý (20 Gün)
    -- 2 = Hýzlý (50 Gün)
    -- 3 = Normal (100 Gün)
    -- 4 = Yavaþ (200 Gün)
    ErosionSpeed = 3,
    -- Erozyonun (gün olarak) yüzde yüze ulaþma süresi. -1 deðeri erozyon olmayacaðý anlamýna gelir. Sýfýr deðeri, Erozyon Hýzý seçeneðini kullanýr. Maksimum 36,500 (100 yýl). Minimum=-1 Maximum=36500 Varsayýlan=0
    ErosionDays = 0,
    -- Bu sayýya göre eylemlerden elde edilen temel XP kazancýný deðiþtirir. Minimum=0,00 Maximum=1000,00 Varsayýlan=1,00
    XpMultiplier = 1.0,
    -- XP çarpanýnýn pasif olarak seviyelendirilmiþ becerileri etkileyip etkilemediðini belirler.Örneðin Fitness ve Güç.
    XpMultiplierAffectsPassive = false,
    -- Bu deðer, motorun genel ses yüksekliðini arttýrmak veya azaltmak için kullanýlýr. Minimum=0,00 Maximum=100,00 Varsayýlan=1,00
    ZombieAttractionMultiplier = 1.0,
    -- Bu deðer true ise, araçlarýn kapýlarý her zaman açýk, benzin depolarý dolu ve motor ses seviyeleri daima düþük olacaktýr.
    VehicleEasyUse = false,
    -- Bitki büyüme hýzýný belirler. Varsayýlan= Normal
    -- 1 = Çok Hýzlý
    -- 2 = Hýzlý
    -- 3 = Normal
    -- 4 = Yavaþ
    Farming = 3,
    -- Yiyeceklerin kompostolarda gübre olmasý için geçen süreyi belirler. Varsayýlan= 2 Hafta
    -- 1 = 1 Hafta
    -- 2 = 2 Hafta
    -- 3 = 3 Hafta
    -- 4 = 4 Hafta
    -- 5 = 6 Hafta
    -- 6 = 8 Hafta
    -- 7 = 10 Hafta
    CompostTime = 2,
    -- Karakterin açlýk, susuzluk ve yorgunluðunun ne kadar hýzlý azalacaðýný tanýmlar. Varsayýlan= Normal
    -- 1 = Çok Hýzlý
    -- 2 = Hýzlý
    -- 3 = Normal
    -- 4 = Yavaþ
    StatsDecrease = 3,
    -- Balýkçýlýk ve araþtýrmanýn zorluk seviyesini etkiler. Varsayýlan= Normal
    -- 1 = Çok Verimsiz
    -- 2 = Verimsiz
    -- 3 = Normal
    -- 4 = Verimli
    NatureAbundance = 3,
    -- Varsayýlan= Bazen
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    Alarm = 4,
    -- Kapýlar ve evlerin pencerelerinin ne kadar sýklýkla kilitli olacaðýný tanýmlar. Varsayýlan= Çok Sýk
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    LockedHouses = 6,
    -- Karakter bir çanta ve kullanýþlý eþyalarla baþlar.
    StarterKit = false,
    -- Gýdalarýn besin deðerleri oyuncunun kondisyonunu etkiler.
    Nutrition = true,
    -- Gýdalarýn buzdolabý içinde veya dýþýnda ne kadar hýzlý bozulacaðýný tanýmlar. Varsayýlan= Normal
    -- 1 = Çok Hýzlý
    -- 2 = Hýzlý
    -- 3 = Normal
    -- 4 = Yavaþ
    FoodRotSpeed = 3,
    -- Dondurmanýn (buzdolabý) ne kadar etkili olacaðýný tanýmlar. Varsayýlan= Normal
    -- 1 = Çok Düþük
    -- 2 = Düþük
    -- 3 = Normal
    -- 4 = Yüksek
    FridgeFactor = 3,
    -- Bir bölgedeki eþyalarýn yeniden doðabilmesi için o bölgeden bir süre uzak durmanýz gerekmektedir. Varsayýlan= Hiçbir Zaman
    -- 1 = Hiçbir Zaman
    -- 2 = Her Gün
    -- 3 = Her Hafta
    -- 4 = Her Ay
    LootRespawn = 1,
    -- Deðer 0'dan büyük olduðunda, bu saat içinde tekrar ziyaret edilen bölgelerde eþyalarýn yeniden doðmasýný önler. Minimum=0 Maximum=2147483647 Varsayýlan=0
    SeenHoursPreventLootRespawn = 0,
    -- Virgül ile ayrýlmýþ her eþya oyunda HoursForWorldItemRemoval süre geçtikten sonra dünyadan silinecektir.
    WorldItemRemovalList = "Base.Hat,Base.Glasses,Base.Maggots",
    -- Kaldýrýlmadan önce bir öðenin yere düþürülmesinden bu yana geçen saat sayýsý. Öðeler, haritanýn o bölümü bir sonraki sefere yüklendiðinde kaldýrýlýr. Sýfýr, öðelerin kaldýrýlmaycaðý anlamýna gelir. Minimum=0,00 Maximum=2147483647,00 Varsayýlan=24,00
    HoursForWorldItemRemoval = 24.0,
    -- Bu ayar açýksa  WorldItemRemovalList listesinde bulunmayan her eþya kaldýrýlacaktýr
    ItemRemovalListBlacklistToggle = false,
    -- Gýda ve erozyon zamanýnýn baþlangýcýný etkiler. Varsayýlan= 0
    -- 1 = 0
    -- 2 = 1
    -- 3 = 2
    -- 4 = 3
    -- 5 = 4
    -- 6 = 5
    -- 7 = 6
    -- 8 = 7
    -- 9 = 8
    -- 10 = 9
    -- 11 = 10
    -- 12 = 11
    TimeSinceApo = 1,
    -- Bu, bitkilerin günde ne kadar su kaybedeceði ve iyileþme yeteneðiyle ilgilidir. Varsayýlan= Normal
    -- 1 = Çok Yüksek
    -- 2 = Yüksek
    -- 3 = Normal
    -- 4 = Az
    PlantResilience = 3,
    -- Tohum baþýna alýnacak ürün sayýsý. Varsayýlan= Normal
    -- 1 = Çok Verimsiz
    -- 2 = Verimsiz
    -- 3 = Normal
    -- 4 = Verimli
    PlantAbundance = 3,
    -- Dinlenme miktarýný belirler. Varsayýlan= Normal
    -- 1 = Çok Hýzlý
    -- 2 = Hýzlý
    -- 3 = Normal
    -- 4 = Yavaþ
    EndRegen = 3,
    -- Helikopterlerin, Olay Bölgesi'nden ne kadar sýklýkla geçeceðini tanýmlar. Varsayýlan= Bir Kez
    -- 1 = Hiçbir Zaman
    -- 2 = Bir Kez
    -- 3 = Bazen
    Helicopter = 2,
    -- Rastgele olaylarýn ne kadar sýklýkla olacaðýný tanýmlar.
    -- Helikopter sesi ve silah ateþlenmesi gibi olaylar meydana gelebilir ve zombiler o yöne doðru hareket edebilir. Varsayýlan= Bazen
    -- 1 = Hiçbir Zaman
    -- 2 = Bazen
    MetaEvent = 2,
    -- Oyuncunun uykusu sýrasýnda ne kadar sýklýkla rastgele olaylar olacaðýný tanýmlar. Varsayýlan= Hiçbir Zaman
    -- 1 = Hiçbir Zaman
    -- 2 = Bazen
    SleepingEvent = 1,
    -- Jeneratörlerin harita üzerindeki daðýlýmýný tanýmlar. Varsayýlan= Bazen
    -- 1 = Çok Nadir
    -- 2 = Nadir
    -- 3 = Bazen
    -- 4 = Sýk
    GeneratorSpawning = 3,
    -- Jeneratörlerin ne kadar yakýt tüketeceðini etkiler. Jeneratörler yakýt tüketmesin istiyorsanýz, bu deðeri 0.0 olarak ayarlamalýsýnýz. Minimum=0,00 Maximum=100,00 Varsayýlan=1,00
    GeneratorFuelConsumption = 1.0,
    -- Haritada ne kadar sýklýkla rastgele oluþturulmuþ evler olacaðýný tanýmlar. Bu bölgelerde barikatlar, yanmýþ alanlar, yaðmalanmýþ eþyalar, ölü cesetler vb. bulunabilir. Varsayýlan= Nadir
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    SurvivorHouseChance = 3,
    -- Varsayýlan= Nadir
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    VehicleStoryChance = 3,
    -- Varsayýlan= Nadir
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    ZoneStoryChance = 3,
    -- Ölü insanlarýn ve zombilerin üzerinden ne kadar sýklýkla açýklamalý harita çýkacaðýný tanýmlar. Varsayýlan= Bazen
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    AnnotatedMapChance = 4,
    -- Karakter oluþturma sýrasýnda oyuncuya ekstra özellik puaný ekler. Minimum=-100 Maximum=100 Varsayýlan=0
    CharacterFreePoints = 0,
    -- Oyuncu yapýlarýna ekstra dayanýklýlýk puaný verir, böylece zombi saldýrýlarýna karþý daha dirençli olurlar. Varsayýlan= Normal
    -- 1 = Çok Düþük
    -- 2 = Düþük
    -- 3 = Normal
    -- 4 = Yüksek
    ConstructionBonusPoints = 3,
    -- Geceleri ortam aydýnlatmasýný belirler. Varsayýlan= Normal
    -- 1 = Çok Karanlýk
    -- 2 = Karanlýk
    -- 3 = Normal
    NightDarkness = 3,
    -- Þafaktan Alacakaranlýða kadarki olan zamaný belirler. Varsayýlan= Normal
    -- 1 = Her zaman Gece
    -- 2 = Uzun
    -- 3 = Normal
    -- 4 = Kýsa
    NightLength = 3,
    -- Yaralanmalarýn vücudunuz üzerindeki etkisini ve iyileþme sürecini etkiler. Varsayýlan= Normal
    -- 1 = Düþük
    -- 2 = Normal
    InjurySeverity = 2,
    -- Mücadelecilerin yüksek bir yerden düþme, zombi tarafýndan alýnan sert bir darbe vb. gibi durumlar sonucunda oluþacak kemik kýrýlma faktörünü etkin kýlar veya devre dýþý býrakýr.
    BoneFracture = true,
    -- Zombi cesetlerinin, haritadan otomatik olarak kaldýrýlmadan önce beklenecek saat sayýsý.
    -- (Eski HoursForCorpseRemoval adlý sunucu ayarýnýn yerini alýr). Minimum=-1,00 Maximum=2147483647,00 Varsayýlan=216,00
    HoursForCorpseRemoval = 216.0,
    -- Yakýnlardaki cesetlerin, oyuncu saðlýðýna ve duygularýna etki edip etmeyeðini tanýmlar. Varsayýlan= Normal
    -- 1 = Yok
    -- 2 = Düþük
    -- 3 = Normal
    DecayingCorpseHealthImpact = 3,
    -- Yere ve duvarlara ne kadar kan sýçrayacaðýný belirler Varsayýlan= Normal
    -- 1 = Yok
    -- 2 = Düþük
    -- 3 = Normal
    -- 4 = Yüksek
    BloodLevel = 3,
    -- Giysilerin ne kadar hýzla kirleneceðini geleceðini tanýmlar. (Kapatýlabilir.) Varsayýlan= Normal
    -- 1 = Kapalý
    -- 2 = Yavaþ
    -- 3 = Normal
    ClothingDegradation = 3,
    FireSpread = true,
    -- Bu, çürümüþ gýdalarýn haritadan kaç gün sonra silineceðini tanýmlar. -1 deðeri, çürümüþ gýdalarýn haritadan asla silinmeyeceði anlamýna gelmektedir. Minimum=-1 Maximum=2147483647 Varsayýlan=-1
    DaysForRottenFoodRemoval = -1,
    -- Etkinleþtirilirse, jeneratörler izin verilen dýþ mekânlarda çalýþacaktýr; örneðin elektrikle çalýþan benzin pompalarý vb. gibi.
    AllowExteriorGenerator = true,
    -- Sisin maksimum yoðunluðunu belirler. Varsayýlan= Normal
    -- 1 = Normal
    -- 2 = Ilýmlý
    MaxFogIntensity = 1,
    -- Yaðmurun maksimum yoðunluðunu kontrol eder. Varsayýlan= Normal
    -- 1 = Normal
    -- 2 = Ilýmlý
    MaxRainFxIntensity = 1,
    -- Devre dýþý býrakýlýrsa kar yerde birikmeyecek, ancak bitki örtüsü ve çatýlarda görünmeye devam edecektir.
    EnableSnowOnGround = true,
    -- Etkinleþtirildiðinde, belirli yakýn dövüþ silahlarý tek vuruþta birden fazla zombiyi vurabilir.
    MultiHitZombies = false,
    -- Bir zombi arkadan saldýrdýðýnda ýsýrýlma þansý. Varsayýlan= Yüksek
    -- 1 = Düþük
    -- 2 = Orta
    RearVulnerability = 3,
    -- Yakýn dövüþ saldýrýsý sýrasýnda engelsiz yürümeyi devre dýþý býrakýn.
    AttackBlockMovements = true,
    AllClothesUnlocked = false,
    -- Eðer kapalýysa,Kontamine suyu normal sudan ayýrt edemezsiniz.
    EnableTaintedWaterText = true,
    -- Haritada arabalarýn ne sýklýkta keþfedildiðini belirler. Varsayýlan= Normal
    -- 1 = Hiçbir Zaman
    -- 2 = Düþük
    -- 3 = Normal
    -- 4 = Yüksek
    CarSpawnRate = 3,
    -- Deposu benzin dolu araçlarýn ne sýklýkla bulunacaðýný tanýmlar. Varsayýlan= Düþük
    -- 1 = Düþük
    -- 2 = Normal
    ChanceHasGas = 1,
    -- Yeni keþfedilen araçlarda, deponun ne kadar dolu olacaðýný tanýmlar. Varsayýlan= Az
    -- 1 = Çok Az
    -- 2 = Az
    -- 3 = Normal
    -- 4 = Çok
    -- 5 = Çok Fazla
    InitialGas = 2,
    -- Akaryakýt Ýstasyonundaki Benzin Depolarýnýn Ne Kadar Dolu Olacaðýný Belirler Varsayýlan= Normal
    -- 1 = Boþ
    -- 2 = Neredeyse Yok
    -- 3 = Çok Az
    -- 4 = Az
    -- 5 = Normal
    -- 6 = Yüksek
    -- 7 = Çok Yüksek
    -- 8 = Tam Dolu
    FuelStationGas = 5,
    -- Araçlarýn ortalama ne kadar çok yakacaðýný belirler. Minimum=0,00 Maximum=100,00 Varsayýlan=1,00
    CarGasConsumption = 1.0,
    -- Varsayýlan= Nadir
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    LockedCar = 3,
    -- Araçlarýn ne durumda doðacaðýný tanýmlar. Varsayýlan= Kötü
    -- 1 = Çok Kötü
    -- 2 = Kötü
    -- 3 = Normal
    -- 4 = Ýyi
    CarGeneralCondition = 2,
    -- Kaza yapan araçlarýn ne kadar hasar alacaðýný tanýmlar. Varsayýlan= Normal
    -- 1 = Çok Az
    -- 2 = Az
    -- 3 = Normal
    -- 4 = Yüksek
    CarDamageOnImpact = 3,
    -- Bir çarpýþmada arabadaki oyuncudan alýnan hasar Varsayýlan= Yok
    -- 1 = Yok
    -- 2 = Düþük
    -- 3 = Normal
    -- 4 = Yüksek
    DamageToPlayerFromHitByACar = 1,
    -- Haritanýn ana yollarýnda, araçlarýn yarattýðý trafik sýkýþýklýðýný etkinleþtirir veya devre dýþý býrakýr.
    TrafficJam = true,
    -- Bir arabanýn alarmlý olarak ne sýklýkla keþfedileceðini belirler. Varsayýlan= Çok Nadir
    -- 1 = Hiçbir Zaman
    -- 2 = Çok Nadir
    -- 3 = Nadir
    -- 4 = Bazen
    -- 5 = Sýk
    CarAlarm = 2,
    -- Aracýn bir oyuncuya çarpmasýndan dolayý oluþabilecek hasarlarý etkinleþtirin veya devre dýþý býrakýn.
    PlayerDamageFromCrash = true,
    -- Siren sesinin durmasý için gereken saat sayýsý. 0.0 deðeri, akü bitene kadar sirenin çalacaðý anlamýna gelir. Minimum=0,00 Maximum=168,00 Varsayýlan=0,00
    SirenShutoffHours = 0.0,
    -- Oyuncunun, kýyametin yayýlmasý ile birlikte bakýmlý ve sahibi olan araçlarý keþfetme þansýnýn ne kadar olacaðýný tanýmlar. Varsayýlan= Az
    -- 1 = Yok
    -- 2 = Az
    -- 3 = Normal
    RecentlySurvivorVehicles = 2,
    -- Araçlarýn haritada ortaya çýkmasýný saðlar.
    EnableVehicles = true,
    -- Besin Zehirlenmesini Belirler. Varsayýlan= Evet
    -- 1 = Evet
    -- 2 = Hayýr
    EnablePoisoning = 1,
    -- Varsayýlan= Ýçinde ve Çevresinde
    -- 1 = Ýçinde ve Çevresinde
    -- 2 = Sadece içinde
    MaggotSpawn = 1,
    -- Deðer ne kadar büyükse ömürleri o kadar artar. Bu deðer 0 olursa asla kýrýlmazlar. Araç farlarýndaki ampul bu ayara tabi deðildir. Minimum=0,00 Maximum=1000,00 Varsayýlan=1,00
    LightBulbLifespan = 1.0,
    Map = {
        AllowMiniMap = false,
        AllowWorldMap = true,
        MapAllKnown = false,
    },
    ZombieLore = {
        -- Zombi hareket hýzýný belirler Varsayýlan= Hýzlý Yürüme
        -- 1 = Koþucular
        -- 2 = Hýzlý Yürüme
        -- 3 = Yürüme
        Speed = 2,
        -- Zombilerin ne kadar güçlü saldýrýlar yapacaðýný belirler. Varsayýlan= Normal
        -- 1 = Ýnsanüstü
        -- 2 = Normal
        -- 3 = Zayýf
        Strength = 2,
        -- Zombileri öldürmenin zorluðunu belirler. Varsayýlan= Normal
        -- 1 = Dayanýklý
        -- 2 = Normal
        -- 3 = Kýrýlgan
        Toughness = 2,
        -- Zombi virüsünün nasýl yayýlacaðýný belirler. Varsayýlan= Kan + Salya
        -- 1 = Kan + Salya
        -- 2 = Sadece Salya
        -- 3 = Herkes Enfekte
        Transmission = 1,
        -- Enfeksiyonun ne kadar hýzlý etkisini göstereceðini belirler. Varsayýlan= 2-3 Gün
        -- 1 = Anlýk
        -- 2 = 0-30 Saniye
        -- 3 = 0-1 Dakika
        -- 4 = 0-12 Saat
        -- 5 = 2-3 Gün
        -- 6 = 1-2 Hafta
        Mortality = 5,
        -- Cesetlerin zombi olarak kalkmadan önce yerde ne kadar kalacaðýný belirler. Varsayýlan= 0-1 Dakika
        -- 1 = Anlýk
        -- 2 = 0-30 Saniye
        -- 3 = 0-1 Dakika
        -- 4 = 0-12 Saat
        -- 5 = 2-3 Gün
        Reanimate = 3,
        -- Zombilerin ne kadar zeki olacaklarýný belirler Varsayýlan= Basit Yön Bulma
        -- 1 = Yön Bulma + Kapý Açma
        -- 2 = Yön Bulma
        -- 3 = Basit Yön Bulma
        Cognition = 3,
        -- Zombilerin ne kadar sýklýkla araçlarýn altýndan sürünerek geçebileceðini belirler. Varsayýlan= Sýk
        -- 1 = Asla
        -- 2 = Aþýrý Nadir
        -- 3 = Nadir
        -- 4 = Bazen
        -- 5 = Sýk
        -- 6 = Çok Sýk
        CrawlUnderVehicle = 5,
        -- Zombilerin gördükten veya duyduktan sonra oyuncularý ne kadar süre hatýrlayacaðýný belirler. Varsayýlan= Normal
        -- 1 = Uzun
        -- 2 = Normal
        -- 3 = Kýsa
        -- 4 = Yok
        Memory = 2,
        -- Zombi görüþ mesafesini belirler. Varsayýlan= Normal
        -- 1 = Keskin
        -- 2 = Normal
        -- 3 = Zayýf
        Sight = 2,
        -- Zombi iþitme mesafesini belirler. Varsayýlan= Normal
        -- 1 = Keskin
        -- 2 = Normal
        -- 3 = Zayýf
        Hearing = 2,
        -- Zombiler serbest dolaþýrken oyuncuyu görmeden/duymadan kapýlara ve etraftaki yapýlara saldýrabilir.
        ThumpNoChasing = false,
        -- Zombilerin, oyuncunun inþa ettiði yapýlara ve barikatlara zarar verip veremeyeceðini tanýmlar.
        ThumpOnConstruction = true,
        -- Zombilerin günün hangi saatlerinde aktif olup olmayacaðýný tanýmlar. Pasif zombiler daha yavaþ ve peþinize takýlmaya daha az meyilli olurlar. Varsayýlan= Her Ýkiside
        -- 1 = Her Ýkiside
        -- 2 = Gece
        ActiveOnly = 1,
        -- Zombilerin kapý veya pencereleri kýrarak ev alarmlarýný etkinleþtirmesine izin verir.
        TriggerHouseAlarm = false,
        -- Aktif edildiðinde zombi gücüne baðlý olarak birden fazla zombi sana saldýrdýðýnda anýnda öldürmek için seni aþaðý çekebilir.
        ZombiesDragDown = true,
        -- Etkinleþtirildiðinde, çok yakýnsanýz zombiler bir çitin üzerinden geçtikten sonra atýlma þansýna sahip olacaklar.
        ZombiesFenceLunge = true,
        -- Varsayýlan= Bazý Zombiler Ölü Taklidi Yaparlar.
        -- 1 = Bazý Zombiler Ölü Taklidi Yaparlar.
        -- 2 = Bazý zombiler ve sizin 'öldürdüðünüz 'Bazý Zombiler
        DisableFakeDead = 1,
    },
    ZombieConfig = {
        -- Bu ayar \Zombi Nüfusu\ ayarýna göre belirlenmektedir. Oyundaki Zombi Yoðunluðunu Belirler Minimum=0,00 Maximum=4,00 Varsayýlan=1,00
        PopulationMultiplier = 1.0,
        -- Oyunun baþýnda istenilen zombi yoðunluðu. Minimum=0,00 Maximum=4,00 Varsayýlan=1,00
        PopulationStartMultiplier = 1.0,
        -- Bu Deðer Nüfus Sýnýrýna Ulaþýlacak Güne Geldiðinde Baþlangýç Nüfus Çarpaný Deðerinin Yerini Alýr. Minimum=0,00 Maximum=4,00 Varsayýlan=1,50
        PopulationPeakMultiplier = 1.5,
        -- Baþlangýç Nüfusu Çarpaný Deðerinden Nüfus Sýnýrý Çarpaný Deðerine Kaç Günde Ulaþýlacaðýný Belirler. Minimum=1 Maximum=365 Varsayýlan=28
        PopulationPeakDay = 28,
        -- Zombilerin bölgelerde tekrar doðmasý için geçmesi gereken saat sayýsý. Sýfýrlanýrsa yeniden doðma kapanýr. Minimum=0,00 Maximum=8760,00 Varsayýlan=72,00
        RespawnHours = 72.0,
        -- Daha önce zombilerin sizi görmediði saatlerde etrafýnýzda doðacak zombi sayýsý. Minimum=0,00 Maximum=8760,00 Varsayýlan=16,00
        RespawnUnseenHours = 16.0,
        -- Her Doðma Saatinde yeniden doðma olabilecek bir yerde istenilen zombi yoðunluðu. Minimum=0,00 Maximum=1,00 Varsayýlan=0,10
        RespawnMultiplier = 0.1,
        -- Zombilerin bulunduklarý yerden göç etmesi için geçmesi gereken saat sayýsý. Minimum=0,00 Maximum=8760,00 Varsayýlan=12,00
        RedistributeHours = 12.0,
        -- Zombiler belirlenen mesafe içindeki en son duyuklarý sese doðru hareketlenecektir. Minimum=10 Maximum=1000 Varsayýlan=100
        FollowSoundDistance = 100,
        -- Zombilerin boþta iken oluþturacaklarý grubun boyutudur. Sýfýra alýrsanýz zombiler grup oluþturmayacaktýr. Gruplar, bina içinde veya orman bölgelerinde oluþmaz. Minimum=0 Maximum=1000 Varsayýlan=20
        RallyGroupSize = 20,
        -- Zombilerin boþta iken gruplara ilerleme mesafesi. Minimum=5 Maximum=50 Varsayýlan=20
        RallyTravelDistance = 20,
        -- Zombi gruplarýnýn arasýndaki uzaklýk. Minimum=5 Maximum=25 Varsayýlan=15
        RallyGroupSeparation = 15,
        -- Grup üyeleri grup liderine ne kadar yakýn olsun? Minimum=1 Maximum=10 Varsayýlan=3
        RallyGroupRadius = 3,
    },
}
